[[ecoMain]]
    Type = EmonHubEcoMainInterfacer
    [[[init_settings]]]
        host = 192.168.1.50
        serial = 001234567890
        timeout = 3
    [[[runtimesettings]]]
        pubchannels = ToEmonCMS,
        read_interval = 10
        [[[[meters]]]]
            [[[[[grid]]]]]
                nodeid = 30
                nodename = ecomain_grid
                source = grid
            [[[[[pv]]]]]
                nodeid = 31
                nodename = ecomain_pv
                source = branches
                phases = 0:1:false, 0:2:false, 0:3:false
            [[[[[heatpump]]]]]
                nodeid = 32
                nodename = ecomain_heatpump
                source = branches
                phases = 1:4:true
