[[SPI]]
    Type = EmonHubRF69Interfacer
    [[[init_settings]]]
        nodeid = 5
        group = 210
        format = 2        # 1 = JeeLib classic, 2 = JeeLib native
        resetPin = 24     # remove line if hardware is emonBase RFM69 SPI
        selPin = 16       # remove line or change to selPin = 26 if hardware is emonBase RFM69 SPI
    [[[runtimesettings]]]
        pubchannels = ToEmonCMS,
