#!/bin/sh

echo "Emonhub installation script for emonPi"

### set git cloned location
GIT_PATH=/home/debian/emonhub

if [ ! -d /home/debian ] ; then
  {
    echo "Directory /home/debian does not exist, this installation script is for raspberrypi installation"
    exit
  }
fi


### set location to install emonhub.py etc
INST_PATH=/usr/share/emonhub

### create linked directory for emonhub.py etc
sudo rm -r -f $INST_PATH
sudo ln -s $GIT_PATH/src $INST_PATH

### link init script
sudo rm -f /etc/init.d/emonhub
sudo ln -s $GIT_PATH/service/emonhub /etc/init.d/emonhub

### link default locations file
sudo rm -f /etc/default/emonhub
sudo ln -s $GIT_PATH/conf/default/emonhub /etc/default/emonhub

### create folder and move settings file (unless it exists already)
if [ ! -f /home/debian/data/emonhub.conf ] ; then
  {
    sudo mv $GIT_PATH/conf/emonhub.conf /home/debian/data/emonhub.conf
  }
fi

# launch at start-ip
sudo update-rc.d emonhub defaults 99

###install dependancies


wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key
cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-jessie.list
cd ~/
sudo apt-get update

sudo apt-get install -y python-serial python-configobj mosquitto python-pip
sudo pip install paho-mqtt
sudo pip install pydispatcher


### create "emonhub" user
sudo useradd -M -r -G dialout,tty -c "emonHub user" emonhub
